language: elixir

elixir: 1.5.0
otp_release: 20.0

dist: trusty
sudo: false
addons:
  postgresql: 9.6

env:
  - MIX_ENV=test

cache:
  directories:
    - _build
    - deps

before_script:
  - mix deps.compile

script:
  - mix compile --warnings-as-errors
  - mix dogma
  - mix credo --strict
  - mix coveralls.travis
